corrections = {
    'VW': 'VOLKSWAGEN',
    'VOLKSWAGEN. VW': 'VOLKSWAGEN',
    'VOLKSWAGEN-VW': 'VOLKSWAGEN',
    'VOLKSWAGEN-VW VOLKSWAGEN. VW': 'VOLKSWAGEN',
    'MERCEDES-BENZ': 'MERCEDES',
    'MERCEDES BENZ': 'MERCEDES',
    'BAYER.MOT.WERKE-BMW': 'BMW',
    'BMW AG': 'BMW',
    'BMW I': 'BMW',
    'DAIMLERCHRYSLER (D)': 'CHRYSLER',
    'FORD (D)': 'FORD',
    'ROVER': 'LAND ROVER',
    'TOYOTA MEM (B)': 'TOYOTA',
    'SKODA (CZ)': 'SKODA',
    'SEAT (E)': 'SEAT',
    'RENAULT/CARPOL': 'RENAULT',
    'RENAULT (F)': 'RENAULT',
    'VOLVO (S)': 'VOLVO',
    'PEUGEOT (F)': 'PEUGEOT',
    'AUDI AUDI': 'AUDI',
    'FUJI HEAVY IND.(J)': 'SUBARU',
    'NISSAN EUROPE (F)': 'NISSAN',
    'MITSUBISHI (J)': 'MITSUBISHI',
    'FORD (D) FORD': 'FORD',
    'KIA MOTOR (ROK)': 'KIA',
    'VOLVO (S) VOLVO': 'VOLVO',
    'TESLA MOTORS': 'TESLA',
    'ADAM OPEL GMBH': 'OPEL',
    'SKODA (CZ) SKODA': 'SKODA',
    'HYUNDAI MOTOR (ROK)': 'HYUNDAI',
    'JAGUAR LAND ROVER LIMITED': 'LAND ROVER',
    'OPEL OPEL': 'OPEL',
    'BAYER.MOT.WERKE-BMW BMW': 'BMW',
    'CITROEN (F)': 'CITROEN',
    'B.M.W.': 'BMW',
    'MAZDA (J)': 'MAZDA',
    'FIAT (I)': 'FIAT',
    'DAIMLERCHRYSLER (USA)': 'CHRYSLER',
    'HONDA MOTOR (J)': 'HONDA',
    'DAIMLERCHRYSLER AG': 'CHRYSLER',
    'FORD W GMBH': 'FORD',
    'MERCEDES-AMG': 'MERCEDES',
    'HONDA (GB)': 'HONDA',
    'LANDROVER': 'LAND ROVER',
    'DAIMLER AG': 'MERCEDES',
    'TOYOTA EUROPE (B)': 'TOYOTA',
    'FUJI HEAVY IND. (J)': 'SUBARU',
    'ALFA': 'ALFA ROMEO',
    'DS': 'CITROEN',
    'SSANGYONG': 'SSANG YONG'
}

corrections_models = {
    'AUDI A6': 'A6',
    'AUDI A4': 'A4',
    'AUDI A3': 'A3',
    'TOYOTA RAV4': 'RAV4',
    'TOYOTA AVENSIS': 'AVENSIS',
    'TOYOTA COROLLA': 'COROLLA',
    'TOYOTA AURIS': 'AURIS',
    'TOYOTA C-HR': 'C-HR',
    'TOYOTA YARIS': 'YARIS',
    'TOYOTA COROLLA VERSO': 'COROLLA VERSO',
    'TOYOTA PRIUS': 'PRIUS',
    'NISSAN QASHQAI': 'QASHQAI',
    'NISSAN X-TRAIL': 'X-TRAIL',
    'HONDA CR-V': 'CR-V'
}

colors_update = {
    'PILKA': 'Grey',
    'JUODA': 'Black',
    'MĖLYNA': 'Blue',
    'BALTA': 'White',
    'RAUDONA': 'Red',
    'ŽALIA': 'Green',
    'RUDA': 'Brown'
}